"""Install the local OCR component into ~/.scivane/runtime/ocr.

Two sources, one exit (install()): migrate a legacy deployment (local copy, no network) or
download (upstream first, mirrors on failure). Everything is assembled in a sibling
.partial directory, verified, and swapped in last, so an interrupted install never looks
complete. Fixed files are checked against the sha256 table and Python packages are installed
with --require-hashes, so the source never affects integrity. Downloads resume from a cache.
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile
import time
from pathlib import Path
from typing import Callable
from urllib.parse import urlparse

import httpx

from . import config, runtime
from .i18n import ui
from .runtime import COMPONENT, LEGACY, Artifact, Candidate

#: Progress callback (kind, payload). The route maps kinds to sse.RuntimeEvent;
#: this layer knows nothing about SSE.
Report = Callable[[str, dict], None]

#: Shipped with the code; generated by `build_backend.sh lock`.
OCR_LOCK = Path(__file__).with_name("requirements-ocr.txt")

# Switch sources when the average rate is still below this after that many seconds (except on
# the last source). Timeouts alone miss a mirror that connects fine but trickles at a few KB/s.
SLOW_AFTER_SECONDS = 20.0
SLOW_BYTES_PER_SECOND = 150_000

# Files are cloned from the download cache (no new blocks on APFS), so models count once.
SITE_ESTIMATE_BYTES = 1_100_000_000
WHEELS_ESTIMATE_BYTES = 270_000_000
DISK_MARGIN_BYTES = 512_000_000


class InstallError(Exception):
    def __init__(self, message: str, code: str) -> None:
        super().__init__(message)
        self.code = code


class Cancelled(InstallError):
    def __init__(self) -> None:
        super().__init__(ui("安装已取消（已下载的部分留在缓存里，下次接着下）",
                            "Install canceled (what's downloaded stays cached; next time it resumes)"),
                         "CANCELLED")


def _quiet(_kind: str, _payload: dict) -> None:
    pass


def install(method: str, dest: Path, *, report: Report = _quiet,
            should_stop: Callable[[], bool] = lambda: False) -> Path:
    if method == "migrate":
        # An unset legacy location is the same named failure as an incomplete one;
        # the UI keys off the error code.
        if config.LEGACY_RUNTIME_DIR is None:
            raise InstallError(ui("没有可迁的旧部署（没有设 SCIVANE_LEGACY_RUNTIME_DIR）",
                                  "There's no old deployment to migrate (SCIVANE_LEGACY_RUNTIME_DIR isn't set)"),
                               "LEGACY_INCOMPLETE")
        return migrate_legacy(config.LEGACY_RUNTIME_DIR, dest,
                              log=lambda msg: report("log", {"message": msg}))
    if method == "download":
        return install_download(dest, report=report, should_stop=should_stop)
    raise InstallError(ui(f"不认识的安装方式：{method!r}", f"Unknown install method: {method!r}"),
                       "BAD_METHOD")


def migrate_legacy(source: Path, dest: Path, *, log: Callable[[str], None] = lambda _msg: None) -> Path:
    """Copy a legacy deployment into the component layout without touching the original."""
    legacy = Candidate("legacy", source, LEGACY)
    problem = legacy.problem()
    if problem is not None:
        raise InstallError(ui(f"旧部署不齐，没法迁：{problem}",
                              f"The old deployment is incomplete, so it can't be migrated: {problem}"),
                           "LEGACY_INCOMPLETE")

    stage = _fresh_stage(dest)
    try:
        target = Candidate("component", stage, COMPONENT)
        for item in runtime.COMPONENTS:
            src, dst = _copy_pair(legacy, target, item)
            log(ui(f"拷贝 {item.label}", f"Copying {item.display_label}"))
            dst.parent.mkdir(parents=True, exist_ok=True)
            _clone(src, dst)
        # paddlex's HuggingFace download cache is not part of the model.
        shutil.rmtree(target.layout_dir / ".cache", ignore_errors=True)
        verify(target, log=log)
        _write_manifest(stage, source=f"migrated:{source}")
        leftover = target.problem()
        if leftover is not None:
            raise InstallError(ui(f"拷完之后仍然不齐：{leftover}",
                                  f"Still incomplete after copying: {leftover}"), "STAGE_INCOMPLETE")
        _swap_in(stage, dest)
    except BaseException:
        shutil.rmtree(stage, ignore_errors=True)
        raise
    log(ui(f"已就位：{dest}", f"In place: {dest}"))
    return dest


def verify(target: Candidate, *, log: Callable[[str], None] = lambda _msg: None) -> None:
    """Verify fixed files: size first (cheap), then sha256."""
    for item in runtime.COMPONENTS:
        base = target.location(item)
        for artifact in item.artifacts:
            path = base / artifact.path if artifact.path else base
            if not path.is_file():
                raise InstallError(ui(f"{item.label} 缺文件：{path}",
                                      f"{item.display_label} is missing a file: {path}"), "ARTIFACT_MISSING")
            size = path.stat().st_size
            if size != artifact.size:
                raise InstallError(
                    ui(f"{item.label} 大小不对：{path} 是 {size} 字节，清单是 {artifact.size}",
                       f"{item.display_label} has the wrong size: {path} is {size} bytes, "
                       f"the manifest says {artifact.size}"), "SIZE_MISMATCH")
            log(ui(f"校验 {path.name}（{size / 1e6:.0f} MB）", f"Verifying {path.name} ({size / 1e6:.0f} MB)"))
            digest = _sha256(path)
            if digest != artifact.sha256:
                raise InstallError(
                    ui(f"{item.label} 的 sha256 对不上：{path}\n  实际 {digest}\n  清单 {artifact.sha256}",
                       f"{item.display_label} fails its sha256 check: {path}\n"
                       f"  actual {digest}\n  manifest {artifact.sha256}"),
                    "SHA256_MISMATCH")


def _copy_pair(legacy: Candidate, target: Candidate, item: runtime.Component) -> tuple[Path, Path]:
    if item.key == "python":
        # Legacy records the venv interpreter; copy its site-packages instead. The component has no
        # interpreter: full mode runs the bundled CPython 3.12 with this appended to PYTHONPATH.
        found = sorted((legacy.root / ".venv" / "lib").glob("python3.*/site-packages"))
        if len(found) != 1:
            raise InstallError(ui(f"在 {legacy.root}/.venv 里找不到唯一的 site-packages：{found}",
                                  f"Couldn't find exactly one site-packages in {legacy.root}/.venv: {found}"),
                               "NO_SITE_PACKAGES")
        return found[0], target.location(item)
    if item.key == "llama":
        # llama-server loads its libggml*.dylib via @loader_path, so bin/ moves as a whole.
        return legacy.location(item).parent, target.location(item).parent
    return legacy.location(item), target.location(item)


def _clone(src: Path, dst: Path) -> None:
    # cp -c clones on the same APFS volume and falls back to a copy across volumes;
    # -p keeps llama-server executable.
    result = subprocess.run(["cp", "-Rpc", str(src), str(dst)], capture_output=True, text=True)
    if result.returncode != 0:
        raise InstallError(ui(f"拷贝失败：{src} → {dst}\n{result.stderr.strip()}",
                              f"Copy failed: {src} → {dst}\n{result.stderr.strip()}"), "COPY_FAILED")


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_manifest(stage: Path, *, source: str, sources: dict | None = None) -> None:
    manifest = {
        "schema": runtime.SCHEMA,
        "bundle": runtime.BUNDLE,
        "source": source,
        "installed_at": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
    }
    if sources:
        manifest["sources"] = sources
    (stage / "runtime.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _fresh_stage(dest: Path) -> Path:
    dest.parent.mkdir(parents=True, exist_ok=True)
    # Also sweep leftovers from earlier interrupted runs.
    for stale in dest.parent.glob(f"{dest.name}.partial-*"):
        shutil.rmtree(stale, ignore_errors=True)
    stage = dest.parent / f"{dest.name}.partial-{os.getpid()}"
    stage.mkdir()
    return stage


def _swap_in(stage: Path, dest: Path) -> None:
    """Swap in with two renames, then delete the old copy."""
    old = dest.parent / f"{dest.name}.old-{os.getpid()}"
    if dest.exists():
        dest.rename(old)
    stage.rename(dest)
    shutil.rmtree(old, ignore_errors=True)



def install_download(dest: Path, *, report: Report = _quiet,
                     should_stop: Callable[[], bool] = lambda: False,
                     client: httpx.Client | None = None,
                     pip_install: Callable[..., str] | None = None) -> Path:
    cache = config.DOWNLOADS_DIR
    cache.mkdir(parents=True, exist_ok=True)
    plan = _plan()
    _check_disk(dest, sum(_remaining(cache, a) for _item, a, _to in plan))

    owns_client = client is None
    client = client or httpx.Client(
        follow_redirects=True, timeout=httpx.Timeout(30.0, connect=15.0),
        headers={"User-Agent": "Scivane-OCR-Installer"},
    )
    stage = _fresh_stage(dest)
    target = Candidate("component", stage, COMPONENT)
    used: dict[str, str] = {}
    cached: list[Path] = []
    try:
        steps = _steps(plan)
        for index, (key, label) in enumerate(steps, start=1):
            report("step", {"index": index, "total": len(steps), "key": key, "label": label})
            if key == "python":
                used["python"] = (pip_install or _pip_install)(
                    target.location(runtime.component("python")), report=report, should_stop=should_stop)
                continue
            for item, artifact, to in (entry for entry in plan if entry[0].key == key):
                file = cache / _cache_name(artifact)
                used[f"{key}:{Path(urlparse(artifact.url).path).name}"] = fetch(
                    _sources(artifact.url), file, artifact.size, artifact.sha256,
                    key=key, report=report, should_stop=should_stop, client=client)
                cached.append(file)
                if item.archive is artifact:
                    _unpack(file, target.location(item).parent)
                else:
                    to_path = target.location(item) / to if to else target.location(item)
                    to_path.parent.mkdir(parents=True, exist_ok=True)
                    _clone(file, to_path)
        _strip_quarantine(stage)
        verify(target, log=lambda msg: report("log", {"message": msg}))
        _write_manifest(stage, source="download", sources=used)
        leftover = target.problem()
        if leftover is not None:
            raise InstallError(ui(f"装完之后仍然不齐：{leftover}",
                                  f"Still incomplete after installing: {leftover}"), "STAGE_INCOMPLETE")
        _swap_in(stage, dest)
    except BaseException:
        shutil.rmtree(stage, ignore_errors=True)
        raise
    finally:
        if owns_client:
            client.close()
    # Clear the cache only on success; it is what the next attempt resumes from.
    for file in cached:
        file.unlink(missing_ok=True)
    shutil.rmtree(config.PIP_CACHE_DIR, ignore_errors=True)
    report("log", {"message": ui(f"已就位：{dest}", f"In place: {dest}")})
    return dest


def _plan() -> list[tuple[runtime.Component, Artifact, str]]:
    out = []
    for item in runtime.COMPONENTS:
        if item.archive is not None:
            out.append((item, item.archive, ""))
        for artifact in item.artifacts:
            out.append((item, artifact, artifact.path))
    return out


def _steps(plan: list) -> list[tuple[str, str]]:
    """Small files that expose network problems go first: llama.cpp (GitHub) and the layout model
    (HuggingFace) fail within a minute instead of after 1.8 GB of weights.
    """
    order = ("llama", "layout", "python", "model", "mmproj")
    labels = {item.key: item.display_label for item, _a, _t in plan}
    labels["python"] = runtime.component("python").display_label
    return [(key, labels[key]) for key in order if key in labels]


def _cache_name(artifact: Artifact) -> str:
    # sha256-prefixed so files with the same name but new content never resume each other.
    return f"{artifact.sha256[:16]}-{Path(urlparse(artifact.url).path).name}"


def _remaining(cache: Path, artifact: Artifact) -> int:
    done = cache / _cache_name(artifact)
    if done.is_file():
        return 0
    part = done.with_name(done.name + ".part")
    have = part.stat().st_size if part.is_file() else 0
    return max(artifact.size - have, 0)


def _check_disk(dest: Path, download_bytes: int) -> None:
    need = download_bytes + WHEELS_ESTIMATE_BYTES + SITE_ESTIMATE_BYTES + DISK_MARGIN_BYTES
    where = dest
    while not where.exists() and where != where.parent:
        where = where.parent
    free = shutil.disk_usage(where).free
    if free < need:
        raise InstallError(
            ui(f"装本地 OCR 大约要 {need / 1e9:.1f} GB 空间，{where} 所在的盘只剩 {free / 1e9:.1f} GB",
               f"Installing local OCR needs about {need / 1e9:.1f} GB, "
               f"but the disk holding {where} has only {free / 1e9:.1f} GB free"),
            "DISK_FULL")


def _sources(url: str) -> list[str]:
    """Upstream first, then mirrors. Only HuggingFace has mirrors."""
    upstream = "https://huggingface.co"
    if url.startswith(upstream + "/"):
        return [url] + [mirror.rstrip("/") + url[len(upstream):] for mirror in config.OCR_HF_MIRRORS]
    return [url]


class _SourceFailed(Exception):
    pass


def fetch(sources: list[str], dest: Path, size: int, sha256: str, *, key: str,
          report: Report = _quiet, should_stop: Callable[[], bool] = lambda: False,
          client: httpx.Client) -> str:
    """Download into dest and return the host that completed it.

    Partial data in dest.part resumes across sources; the sha256 check at the end catches mismatches.
    """
    if dest.is_file() and dest.stat().st_size == size and _sha256(dest) == sha256:
        report("log", {"message": ui(f"{dest.name} 已在下载缓存里，校验通过",
                                     f"{dest.name} is already in the download cache and checks out")})
        return "cache"
    part = dest.with_name(dest.name + ".part")
    errors: list[str] = []
    for index, url in enumerate(sources):
        host = urlparse(url).netloc
        last = index == len(sources) - 1
        try:
            _stream(url, part, size, key=key, host=host, report=report,
                    should_stop=should_stop, client=client, may_abandon=not last)
        except _SourceFailed as exc:
            errors.append(ui(f"{host}：{exc}", f"{host}: {exc}"))
            if not last:
                report("source", {"key": key, "from": host, "to": urlparse(sources[index + 1]).netloc,
                                  "reason": str(exc)})
            continue
        if part.stat().st_size != size:
            errors.append(ui(f"{host}：只拿到 {part.stat().st_size} / {size} 字节",
                             f"{host}: got only {part.stat().st_size} / {size} bytes"))
            continue
        if _sha256(part) != sha256:
            # Wrong content invalidates the whole file; the next source starts over.
            part.unlink()
            errors.append(ui(f"{host}：sha256 对不上清单", f"{host}: sha256 doesn't match the manifest"))
            if not last:
                report("source", {"key": key, "from": host, "to": urlparse(sources[index + 1]).netloc,
                                  "reason": ui("sha256 对不上", "sha256 mismatch")})
            continue
        part.rename(dest)
        return host
    raise InstallError(ui(f"{dest.name} 下不下来：\n  ", f"Couldn't download {dest.name}:\n  ")
                       + "\n  ".join(errors), "DOWNLOAD_FAILED")


def _stream(url: str, part: Path, size: int, *, key: str, host: str, report: Report,
            should_stop: Callable[[], bool], client: httpx.Client, may_abandon: bool) -> None:
    offset = part.stat().st_size if part.is_file() else 0
    if offset > size:
        part.unlink()
        offset = 0
    if offset == size:
        return
    headers = {"Range": f"bytes={offset}-"} if offset else {}
    try:
        with client.stream("GET", url, headers=headers) as response:
            if response.status_code == 206:
                mode = "ab"
            elif response.status_code == 200:
                mode, offset = "wb", 0  # source ignores Range: start over
            else:
                raise _SourceFailed(f"HTTP {response.status_code}")
            started = last_report = time.monotonic()
            received = 0
            with part.open(mode) as f:
                # No chunk size: httpx would buffer a full chunk, hiding slow sources and delaying cancellation.
                for chunk in response.iter_bytes():
                    if should_stop():
                        raise Cancelled()
                    f.write(chunk)
                    received += len(chunk)
                    now = time.monotonic()
                    if now - last_report >= 0.25:
                        last_report = now
                        report("progress", {"key": key, "file": part.name.removesuffix(".part"),
                                            "done": offset + received, "total": size, "source": host})
                    elapsed = now - started
                    if may_abandon and elapsed > SLOW_AFTER_SECONDS and received / elapsed < SLOW_BYTES_PER_SECOND:
                        speed = received / elapsed / 1000
                        raise _SourceFailed(ui(f"太慢（{speed:.0f} KB/s）", f"too slow ({speed:.0f} KB/s)"))
            report("progress", {"key": key, "file": part.name.removesuffix(".part"),
                                "done": offset + received, "total": size, "source": host})
    except httpx.HTTPError as exc:
        raise _SourceFailed(f"{type(exc).__name__}: {exc}" if str(exc) else type(exc).__name__) from exc


def _unpack(archive: Path, into: Path) -> None:
    """Unpack the llama.cpp archive, flattening its single top-level directory into `into`.

    filter="data" rejects absolute paths, '..' and links escaping the archive.
    """
    with tempfile.TemporaryDirectory(dir=into.parent if into.parent.exists() else None) as tmp:
        try:
            with tarfile.open(archive) as tar:
                tar.extractall(tmp, filter="data")
        except (tarfile.TarError, OSError) as exc:
            raise InstallError(ui(f"解不开 {archive.name}：{exc}", f"Couldn't unpack {archive.name}: {exc}"),
                               "UNSAFE_ARCHIVE") from exc
        entries = list(Path(tmp).iterdir())
        root = entries[0] if len(entries) == 1 and entries[0].is_dir() else Path(tmp)
        into.mkdir(parents=True, exist_ok=True)
        for entry in root.iterdir():
            entry.rename(into / entry.name)


def _strip_quarantine(path: Path) -> None:
    # Downloaded binaries carry the quarantine flag and would be blocked by Gatekeeper.
    subprocess.run(["xattr", "-dr", "com.apple.quarantine", str(path)], capture_output=True)


def _installer_python() -> str:
    """Interpreter that runs pip, the bundled one first.

    Dev venvs created by uv have no pip, so probe instead of assuming sys.executable.
    """
    for candidate in (config.PYTHON_DIR / "bin" / "python3", Path(sys.executable)):
        if candidate.is_file() and subprocess.run(
                [str(candidate), "-m", "pip", "--version"], capture_output=True).returncode == 0:
            return str(candidate)
    raise InstallError(ui("找不到能装包的 Python（自带解释器还没拷出来，当前解释器里也没有 pip）",
                          "No Python that can install packages (the bundled interpreter isn't copied out yet, "
                          "and the current one has no pip)"), "NO_PIP")


def _pip_install(site: Path, *, report: Report = _quiet,
                 should_stop: Callable[[], bool] = lambda: False) -> str:
    """Install the OCR packages from the lock into `site`; returns the index host used.

    --no-deps: the lock is complete. No --no-compile: the runtime sets PYTHONDONTWRITEBYTECODE,
    so .pyc files must be built here or paddle recompiles on every cold start.
    """
    python = _installer_python()
    total = sum(1 for line in OCR_LOCK.read_text(encoding="utf-8").splitlines() if line[:1].isalpha())
    errors: list[str] = []
    indexes = list(config.OCR_PYPI_INDEXES)
    for index, url in enumerate(indexes):
        host = urlparse(url).netloc
        shutil.rmtree(site, ignore_errors=True)  # retry from scratch; wheels stay in pip's cache
        command = [
            python, "-m", "pip", "--isolated", "--disable-pip-version-check", "install",
            "--no-deps", "--require-hashes", "--only-binary=:all:", "--progress-bar", "off",
            "--target", str(site), "--cache-dir", str(config.PIP_CACHE_DIR),
            "--index-url", url, "--timeout", "30", "--retries", "2", "-r", str(OCR_LOCK),
        ]
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        seen = 0
        tail: list[str] = []
        assert process.stdout is not None
        for line in process.stdout:
            if should_stop():
                process.terminate()
                process.wait()
                raise Cancelled()
            line = line.rstrip()
            tail = (tail + [line])[-8:]
            if line.startswith("Collecting "):
                seen += 1
                report("progress", {"key": "python", "done": seen, "total": total, "unit": "包", "source": host})
            if line.startswith(("Collecting ", "Installing ", "Successfully ")):
                report("log", {"message": line})
        if process.wait() == 0:
            return host
        errors.append(ui(f"{host}：\n    ", f"{host}:\n    ") + "\n    ".join(tail))
        if index < len(indexes) - 1:
            report("source", {"key": "python", "from": host, "to": urlparse(indexes[index + 1]).netloc,
                              "reason": tail[-1] if tail else ui("pip 失败", "pip failed")})
    raise InstallError(ui("OCR 的 Python 依赖装不上：\n  ", "Couldn't install the OCR Python packages:\n  ")
                       + "\n  ".join(errors), "DEPS_FAILED")
